DELETE http://localhost:4200/api/poems/616be3efaace4d528d2cad8a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNmFhOWYyZTExZTNlZTdjZjg2Y2JkZiIsInVzZXJuYW1lIjoiZGFuaWFtMiIsImlhdCI6MTYzNDQ1ODQwOSwiZXhwIjoxNjM1MDYzMjA5fQ.rgYkBwJJ2SmiXGEcXesvNONCP3_gVCVSQ2Y1tF--Z7w