# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React CI/CD

on:
  push:
    branches: [ feature/token ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SKIP_PREFLIGHT_CHECK: true
      GENERATE_SOURCEMAP: false

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
          run:
            working-directory: ./Poemunity-React-Query/frontend

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: ls
    # - run: npm clean-install
    - run: npm cache clean --force
    - run: npm ci
    # - run: npm test
    - run: npm run build --verbose
  
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd projects/poemunity        
          git pull
          git status


